# This is a basic workflow to help you get started with Actions

name: Python Schedules Script

# Controls when the workflow will run
on:
  schedule:
  - cron: "5 * * * *"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path : "requirements.txt"
        
      - name: Run Script
        run: python test.py
        
      - name: Commit Files
        run:
          git config --local user.name jhkersting
          git config --local user.email jhkersting@crimson.ua.edu
          git add --all
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
      
      
          

