# This is a basic workflow to help you get started with Actions

name: Python Schedules Script

# Controls when the workflow will run
on:
  schedule:
  - cron: "5 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path : "requirements.txt"
        
      - name: Run Script
        run: test.py
        
      - name: Commit Files
        run:
          git config --local user.name jhkersting
          git config --local user.email jhkersting@crimson.ua.edu
          git add --all
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
      
      
          

